name: Cross Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Building skynet for Windows amd64..."
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o skynet.exe
          echo "skynet.exe built"
          
          echo "Building skynet for Linux arm64..."
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o skynet-arm64
          echo "skynet-arm64 built"
          
          echo "Building skynet for Linux amd64..."
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o skynet-amd64
          echo "skynet-amd64 built"
          
          echo "Building skynet for Linux arm..."
          GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -o skynet-arm
          echo "skynet-arm built"
          
          echo "Building skynet for Linux 386..."
          GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o skynet-386
          echo "skynet-386 built"
          
          echo "Building skynet for Linux ppc64le..."
          GOOS=linux GOARCH=ppc64le CGO_ENABLED=0 go build -o skynet-ppc64le
          echo "skynet-ppc64le built"
          
          echo "Building skynet for Linux ppc64..."
          GOOS=linux GOARCH=ppc64 CGO_ENABLED=0 go build -o skynet-ppc64
          echo "skynet-ppc64 built"
          
          echo "Building skynet for Linux mips64le..."
          GOOS=linux GOARCH=mips64le CGO_ENABLED=0 go build -o skynet-mips64le
          echo "skynet-mips64le built"
          
          echo "Building skynet for Linux mips64..."
          GOOS=linux GOARCH=mips64 CGO_ENABLED=0 go build -o skynet-mips64
          echo "skynet-mips64 built"
          
          echo "Building skynet for Linux mipsle..."
          GOOS=linux GOARCH=mipsle CGO_ENABLED=0 go build -o skynet-mipsle
          echo "skynet-mipsle built"
          
          echo "Building skynet for Linux mips..."
          GOOS=linux GOARCH=mips CGO_ENABLED=0 go build -o skynet-mips
          echo "skynet-mips built"
          
          echo "Building skynet for Darwin amd64..."
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o skynet-darwin-amd64
          echo "skynet-darwin-amd64 built"
          
          echo "Building skynet for Darwin arm64..."
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o skynet-darwin-arm64
          echo "skynet-darwin-arm64 built"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            skynet.exe
            skynet-arm64
            skynet-amd64
            skynet-arm
            skynet-386
            skynet-ppc64le
            skynet-ppc64
            skynet-mips64le
            skynet-mips64
            skynet-mipsle
            skynet-mips
            skynet-darwin-amd64
            skynet-darwin-arm64