name: Cross Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Building JingYong_Meet for Windows 386..."
          GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -o JingYong_Meet-windows-386
          echo "JingYong_Meet-windows-386 built"
          echo "Building JingYong_Meet for Windows amd64..."
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o JingYong_Meet-windows-amd64
          echo "JingYong_Meet-windows-amd64 built"
          echo "Building JingYong_Meet for Windows arm..."
          GOOS=windows GOARCH=arm CGO_ENABLED=0 go build -o JingYong_Meet-windows-arm
          echo "JingYong_Meet-windows-arm built"
          echo "Building JingYong_Meet for Windows arm64..."
          GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build -o JingYong_Meet-windows-arm64
          echo "JingYong_Meet-windows-arm64 built"
          echo "Building JingYong_Meet for Linux 386..."
          GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o JingYong_Meet-linux-386
          echo "JingYong_Meet-linux-386 built"
          echo "Building JingYong_Meet for Linux amd64..."
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o JingYong_Meet-linux-amd64
          echo "JingYong_Meet-linux-amd64 built"
          echo "Building JingYong_Meet for Linux arm..."
          GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -o JingYong_Meet-linux-arm
          echo "JingYong_Meet-linux-arm built"
          echo "Building JingYong_Meet for Linux arm64..."
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o JingYong_Meet-linux-arm64
          echo "JingYong_Meet-linux-arm64 built"
          echo "Building JingYong_Meet for Linux s390x..."
          GOOS=linux GOARCH=s390x CGO_ENABLED=0 go build -o JingYong_Meet-linux-s390x
          echo "JingYong_Meet-linux-s390x built"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
         name: build-artifacts
         path: |
          JingYong_Meet-windows-386
          JingYong_Meet-windows-amd64
          JingYong_Meet-windows-arm
          JingYong_Meet-windows-arm64
          JingYong_Meet-linux-386
          JingYong_Meet-linux-amd64
          JingYong_Meet-linux-arm
          JingYong_Meet-linux-arm64
          JingYong_Meet-linux-s390x